### ISSUE TITLE
Problem with review system.

### ISSUE THREAD

**Issue by furkanndgn** [CAPELLAX02/grocery-app-backend#1]
When a user change his username, username that stored in his old reviews remain unchanged. Because of this bug, a user can write more than one review for a product using different usernames.

**Comment by CAPELLAX02** [comment]
Thank you for pointing out this issue! The problem with the review system has been resolved in [commit 9a98fe1](https://github.com/CAPELLAX02/grocery-app-backend/commit/9a98fe1). 

Now, when a user updates their username, the username stored in their old reviews is also updated. This ensures that users cannot submit multiple reviews for the same product by changing their username.

Let me know if you encounter any other issues or if you have further feedback. Thanks again for your contribution! 😊
